spring:
  profiles:
    active: local
    batch:
      job:
        names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    generate-ddl: false
    hibernates:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
external :
  apartment-api:
    path: http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: EdMKj6557yVIaHWPV1kkI6fxXtXSC8tUcX0QO%2FPxAT6tsSnPUg92SDyD4spHDeVf1yAiC2cmlYMQx5Mw%2FllUHg%3D%3D



---
spring:
   config:
     activates:
     on-profile: test
jpa:
  database: h2

